<a href="https://colab.research.google.com/github/aanchaljain1993/Pandas_Practice_Project/blob/main/Census_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/file (8).csv')

# show all records of district is new delhi jaipur and lucknow

In [7]:
df[df['District_name'].isin(['New Delhi','Lucknow','Jaipur'])]

,District_code,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
93,94,NCT OF DELHI,New Delhi,142004,77942,64062,114179,59541,46940,12601,...,4852,2933,312,679,15942,17742,23934,76076,43913,21773
109,110,RAJASTHAN,Jaipur,6626178,3468507,3157671,4300965,2464893,1714947,749946,...,12708,18782,1020,81079,659389,455527,703673,4091148,1646480,884057
156,157,UTTAR PRADESH,Lucknow,4589838,2394476,2195362,3127260,1542806,1226399,316407,...,20493,23883,3877,4975,428121,378742,639260,2678289,1161686,685258

calculate state wise

total number of population


total numbe of popltion of all religion

In [8]:
df.groupby('State_name')['Population'].sum()

State_name
ANDAMAN AND NICOBAR ISLANDS       380581
ANDHRA PRADESH                  84580777
ARUNACHAL PRADESH                1383727
ASSAM                           31205576
BIHAR                          104099452
CHANDIGARH                       1055450
CHHATTISGARH                    25545198
DADRA AND NAGAR HAVELI            343709
DAMAN AND DIU                     243247
GOA                              1458545
GUJARAT                         60439692
HARYANA                         25351462
HIMACHAL PRADESH                 6864602
JAMMU AND KASHMIR               12541302
JHARKHAND                       32988134
KARNATAKA                       61095297
KERALA                          33406061
LAKSHADWEEP                        64473
MADHYA PRADESH                  72626809
MAHARASHTRA                    112374333
MANIPUR                          2855794
MEGHALAYA                        2966889
MIZORAM                          1097206
NAGALAND                         1978502
NCT OF DELHI                    16787941
ORISSA                          41974218
PONDICHERRY                      1247953
PUNJAB                          27743338
RAJASTHAN                       68548437
SIKKIM                            610577
TAMIL NADU                      72147030
TRIPURA                          3673917
UTTAR PRADESH                  199812341
UTTARAKHAND                     10086292
WEST BENGAL                     91276115
Name: Population, dtype: int64

In [10]:
df.groupby('State_name')[['Christians','Sikhs','Buddhists']].sum()

                             Christians     Sikhs  Buddhists
State_name
ANDAMAN AND NICOBAR ISLANDS       80984      1286        338
ANDHRA PRADESH                  1129784     40244      36692
ARUNACHAL PRADESH                418732      3287     162815
ASSAM                           1165867     20672      54993
BIHAR                            129247     23779      25453
CHANDIGARH                         8720    138329       1160
CHHATTISGARH                     490542     70036      70467
DADRA AND NAGAR HAVELI             5113       217        634
DAMAN AND DIU                      2820       172        217
GOA                              366130      1473       1095
GUJARAT                          316178     58246      30483
HARYANA                           50353   1243752       7514
HIMACHAL PRADESH                  12646     79896      78659
JAMMU AND KASHMIR                 35631    234848     112584
JHARKHAND                       1418608     71422       8956
KARNATAKA                       1142647     28773      95710
KERALA                          6141269      3814       4752
LAKSHADWEEP                         317         8         10
MADHYA PRADESH                   213282    151412     216052
MAHARASHTRA                     1080073    223247    6531200
MANIPUR                         1179043      1527       7084
MEGHALAYA                       2213027      3045       9864
MIZORAM                          956331       286      93411
NAGALAND                        1739651      1890       6759
NCT OF DELHI                     146093    570581      18449
ORISSA                          1161708     21991      13852
PONDICHERRY                       78550       297        451
PUNJAB                           348230  16004754      33237
RAJASTHAN                         96430    872930      12185
SIKKIM                            60522      1868     167216
TAMIL NADU                      4418331     14601      11186
TRIPURA                          159882      1070     125385
UTTAR PRADESH                    356448    643500     206285
UTTARAKHAND                       37781    236340      14926
WEST BENGAL                      658618     63523     282898

# how many male in maharshtar

In [19]:
df[df['State_name']=='MAHARASHTRA']['Male'].sum()

58243056

# how to make index district code

In [20]:
df.set_index('District_code')

,State_name,District_name,Population,Male,Female,Literate,Workers,Male_Workers,Female_Workers,Cultivator_Workers,...,Christians,Sikhs,Buddhists,Jains,Secondary_Education,Higher_Education,Graduate_Education,Age_Group_0_29,Age_Group_30_49,Age_Group_50
District_code,,,,,,,,,,,,,,,,,,,,,
1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,229064,190899,38165,34680,...,1700,5600,66,39,74948,39709,21751,600759,178435,89679
2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,214866,162578,52288,55299,...,1489,5559,47,6,66459,41367,27950,503223,160933,88978
3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,75079,53265,21814,20869,...,658,1092,88635,103,16265,8923,6197,70703,41515,21019
4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,51873,39839,12034,8266,...,604,1171,20126,28,16938,9826,3077,87532,35561,17488
5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,161393,117677,43716,54264,...,958,11188,83,10,46062,29517,13962,304979,109818,61334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,PONDICHERRY,Mahe,41816,19143,22673,36470,11802,9093,2709,43,...,958,3,21,14,8773,5711,4475,19760,12543,9428
637,PONDICHERRY,Karaikal,200222,97809,102413,154916,68301,53139,15162,2372,...,18391,46,63,54,29456,15930,18998,102333,60089,37434
638,ANDAMAN AND NICOBAR ISLANDS,Nicobars,36842,20727,16115,25332,17125,12714,4411,322,...,26077,343,119,0,6325,3668,1300,18786,12088,5922
639,ANDAMAN AND NICOBAR ISLANDS,North AND Middle Andaman,105597,54861,50736,78683,38579,30612,7967,10727,...,21870,77,84,4,12707,10042,5133,57350,30741,17464
640,ANDAMAN AND NICOBAR ISLANDS,South Andaman,238142,127283,110859,190266,96831,77563,19268,5518,...,33037,866,135,27,42150,29910,22388,128402,76332,33128